name: GitHub-Actions
run-name: "Plan Process Only"
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'eu-central-1'
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.1.7
          #cli_config_credentials_hostname: 'terraform.example.com'
          #cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          #aws-region: 'eu-central-1'

        #env:
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        # AWS_SECRET_ACCESS_ID: ${{ secrets.AWS_SECRET_KEY }} 
        # AWS_REGION: 'eu-central-1'

      - name: Terraform Format
        id: fmt
        run: terraform fmt 
        
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        run: terraform plan | tee log
        #env:
        #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        #  AWS_SECRET_ACCESS_ID: ${{ secrets.AWS_SECRET_KEY }} 
        #  AWS_REGION: 'eu-central-1' 
      
      - run: cat log
