name: PR-Actions-Final
run-name: "Terraform Plan Process only"
on:
  pull_request:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'eu-central-1'
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.1.7
          cli_config_credentials_hostname: 'terraform.example.com'

      - name: Terraform Format
        id: fmt
        run: terraform fmt 
        
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        run: terraform plan
        
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve

      - name: Sleep process
        id: sleep
        run: sleep 2m

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
